[project]
authors = ["Mitchell Callaghan <mcallaghan345@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Data-Wrangling"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
